# -*- coding: utf-8 -*-
"""python_first_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xieXfAvOWBvrDuGRx4BADZqVt2qofjqI
"""

import random

def get_choices():
  player_choice = input("Enter a choice (rock, paper, scissors:)")
  options = ["rock", "paper", "scissors"]
  computer_choice = random.choice(options)
  choices = {"player": player_choice, "computer": computer_choice}
  return choices

def check_win(player, computer):
  print("You chose" +  player + ", computer chose" + computer)
  if player == computer:
     return"It's a tie!"
  elif player == "rock":
    if computer == "scissors":
      return "Rock smashes scissor! You win!"
    else:
      return "Paper covers rock! You lose."
  elif player == "paper":
    if computer == "rock":
      return "paper covers rock! You win! "
    else:
      return "scissors cuts paper! You lose."

choices = get_choices()
result = check_win(choices["player"], choices["computer"])

